// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxDAcWBPnlMC7TcqkrSUXEv6YnI_2sD9Y',
    appId: '1:81730773002:web:0659c1c0942f2e4e8abff3',
    messagingSenderId: '81730773002',
    projectId: 'usmani-ee963',
    authDomain: 'usmani-ee963.firebaseapp.com',
    storageBucket: 'usmani-ee963.firebasestorage.app',
    measurementId: 'G-44C1BPREZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0OJeEXDSS7guhvuJIbKh3v67yRTzZduI',
    appId: '1:81730773002:android:a88bd26c46ec58bd8abff3',
    messagingSenderId: '81730773002',
    projectId: 'usmani-ee963',
    storageBucket: 'usmani-ee963.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwS6AisJ8-hRyVcOAM1tRstjLSeC9YEHo',
    appId: '1:81730773002:ios:33a4887f8f56604f8abff3',
    messagingSenderId: '81730773002',
    projectId: 'usmani-ee963',
    storageBucket: 'usmani-ee963.firebasestorage.app',
    iosBundleId: 'com.example.babyhubshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwS6AisJ8-hRyVcOAM1tRstjLSeC9YEHo',
    appId: '1:81730773002:ios:33a4887f8f56604f8abff3',
    messagingSenderId: '81730773002',
    projectId: 'usmani-ee963',
    storageBucket: 'usmani-ee963.firebasestorage.app',
    iosBundleId: 'com.example.babyhubshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxDAcWBPnlMC7TcqkrSUXEv6YnI_2sD9Y',
    appId: '1:81730773002:web:798de4013774938c8abff3',
    messagingSenderId: '81730773002',
    projectId: 'usmani-ee963',
    authDomain: 'usmani-ee963.firebaseapp.com',
    storageBucket: 'usmani-ee963.firebasestorage.app',
    measurementId: 'G-83ST3Y67TC',
  );
}
